---
grails:
  profile: rest-api
  codegen:
    defaultPackage: com.bitsoft.st
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
    #tag::multiTenancy[]
    multiTenancy:
      mode: DATABASE
      tenantResolverClass: org.grails.datastore.mapping.multitenancy.web.SessionTenantResolver
    #end::multiTenancy[]

info:
  app:
    name: 'smart-ticketing'
    version: '1.0.0'
    grailsVersion: '3.3.4'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
    upload:
      maxFileSize: 2000000
      maxRequestSize: 2000000
  converters:
    encoding: UTF-8

---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

environments:
  development:
    # tag::dataSources[]
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: ''
      dbCreate: update
      url: jdbc:mysql://localhost/main?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

    dataSources:
      demo:
        url: "jdbc:mysql://localhost/demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      green-dhaka:
        url: "jdbc:mysql://localhost/green-dhaka?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      sb:
        url: "jdbc:mysql://localhost/sb?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
  # end::dataSources[]

  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: bitsoft
      password: "bitSoft@123"
      dbCreate: update
      url: "jdbc:mysql://localhost/main?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 200
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    dataSources:
      demo:
        url: "jdbc:mysql://localhost/demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      green-dhaka:
        url: "jdbc:mysql://localhost/green-dhaka?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      iqbal-ent:
        url: "jdbc:mysql://localhost/iqbal-ent?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      dhaka-chaka:
        url: "jdbc:mysql://localhost/dhaka-chaka?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      utshob:
        url: "jdbc:mysql://localhost/utshob?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      sb:
        url: "jdbc:mysql://localhost/sb?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      mv:
      url: "jdbc:mysql://localhost/mv?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"

      demo-iqbal-ent:
        url: "jdbc:mysql://localhost/demo-iqbal-ent?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      demo-dhaka-chaka:
        url: "jdbc:mysql://localhost/demo-dhaka-chaka?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      demo-green-dhaka:
        url: "jdbc:mysql://localhost/demo-green-dhaka?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      frm:
        url: "jdbc:mysql://localhost/frm?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"
      mbt:
        url: "jdbc:mysql://localhost/mbt?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true"



server:
  port: 8080

grails:
  cors:
    enabled: true